Controllers/AuthedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using login.Identity;
using login.Models;

namespace login.Controllers
{
    
    public class AuthedController : Controller
    {

     
        
     private UserManager<ApplicationUser> _usrMngr;
    private SignInManager<ApplicationUser> _signInMngr;

    public AuthedController(UserManager<ApplicationUser> usrMngr,SignInManager<ApplicationUser> signInMngr)
    {
        _usrMngr = usrMngr;
        _signInMngr = _signInMngr;
        // _context = context;
    }
        public IActionResult Index(){
            if(!User.Identity.IsAuthenticated){

                return RedirectToAction("Login","Account");
                
            }
            
            
            return View();
        }
   public IActionResult homepage()
    {
        if(!User.Identity.IsAuthenticated){

                return RedirectToAction("Login","Account");
                
            }
        return View();
    }
     public IActionResult Profile()
    {
        if(!User.Identity.IsAuthenticated){

                return RedirectToAction("Login","Account");
                
            }
        return View();
    }

        
    }
}

Controllers/CrudController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using login.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using login.Identity;


namespace login.Controllers
{
    public class CrudController : Controller
    {
        private readonly dataofmedContext _context;
        private UserManager<ApplicationUser> _usrMngr;
        private SignInManager<ApplicationUser> _signInMngr;

        public CrudController(UserManager<ApplicationUser> usrMngr,SignInManager<ApplicationUser> signInMngr,dataofmedContext context)
        {
            _context = context;
             _usrMngr = usrMngr;
          _signInMngr = signInMngr;
        }

        // GET: pd
        public async Task<IActionResult> Index()
        {
             if(!User.Identity.IsAuthenticated){

                return RedirectToAction("Login","Account");
                
            }

            return View(await _context.Typesmeds.ToListAsync());

        }

        // GET: pd/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if(!User.Identity.IsAuthenticated){

                return RedirectToAction("Login","Account");
                
            }

            if (id == null)
            {
                return NotFound();
            }

            var @type = await _context.Typesmeds
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@type == null)
            {
                return NotFound();
            }

            return View(@type);
        }

        // GET: pd/Create
        public IActionResult Create()
        {
            if(!User.Identity.IsAuthenticated){

                return RedirectToAction("Login","Account");
                
            }
            
            return View();
        }

        // POST: pd/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Typesmed @type)
        {

            if (ModelState.IsValid)
            {
                _context.Add(@type);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(@type);
        }

        // GET: pd/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if(!User.Identity.IsAuthenticated){

                return RedirectToAction("Login","Account");
                
            }
            if (id == null)
            {
                return NotFound();
            }

            var @type = await _context.Typesmeds.FindAsync(id);
            if (@type == null)
            {
                return NotFound();
            }
            return View(@type);
        }

        // POST: pd/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")]Typesmed @type)
        {
            if (id != @type.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@type);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TypeExists(@type.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@type);
        }

        // GET: pd/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if(!User.Identity.IsAuthenticated){

                return RedirectToAction("Login","Account");
                
            }
            if (id == null)
            {
                return NotFound();
            }

            var @type = await _context.Typesmeds
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@type == null)
            {
                return NotFound();
            }

            return View(@type);
        }

        // POST: pd/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var @type = await _context.Typesmeds.FindAsync(id);
            _context.Typesmeds.Remove(@type);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TypeExists(int id)
        {
            return _context.Typesmeds.Any(e => e.Id == id);
        }
    }

    public class Types
    {
        public int Id { get; internal set; }
    }
}

Views/Crud/Create.cshtml
@model login.Models.Typesmed

@{
    ViewData["Title"] = "Create";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        /* Additional styles if needed */
        /* Adjust colors, backgrounds, or other styles as desired */
        body {
            background-color: #f8f9fa;
            padding-top: 50px;
        }
        h1 {
            color: #007bff;
        }
        .form-group {
            margin-bottom: 20px;
        }
        input[type="submit"] {
            background-color: #007bff;
            color: #fff;
            border: none;
        }
        input[type="submit"]:hover {
            background-color: #0056b3;
        }
        a {
            color: #007bff;
            text-decoration: none;
        }
        a:hover {
            color: #0056b3;
        }
    </style>
</head>
<body>

    <div class="container">
        <h1>Create</h1>
        <h4>Type</h4>
        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </div>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }
</body>
</html>

Views/Crud/Delete.cshtml
@model login.Models.Typesmed

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Type</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Crud/Details.cshtml
@model login.Models.Typesmed

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Type</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Crud/Edit.cshtml
@model login.Models.Typesmed



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    @* <title>Update</title> *@
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        /* Additional styles if needed */
        /* Adjust colors, backgrounds, or other styles as desired */
        body {
            background-color: #f8f9fa;
            padding-top: 50px;
        }
        h1 {
            color: #007bff;
        }
        .form-group {
            margin-bottom: 20px;
        }
        input[type="submit"] {
            background-color: #007bff;
            color: #fff;
            border: none;
        }
        input[type="submit"]:hover {
            background-color: #0056b3;
        }
        a {
            color: #007bff;
            text-decoration: none;
        }
        a:hover {
            color: #0056b3;
        }
    </style>
</head>
<body>

    <div class="container">
        <h1>Update</h1>
        <h4>Type</h4>
        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Id" />
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </div>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }
</body>
</html>

Views/Crud/Index.cshtml
@model IEnumerable<login.Models.Typesmed>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CATEGORY</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" rel="stylesheet">
    <style>
        body {
            background-color: #f8f9fa;
        }
        .container {
            margin-top: 50px;
        }
        .table th {
            background-color: #343a40;
            color: #fff;
        }
        .table-striped tbody tr:nth-of-type(odd) {
            background-color: #f8f9fa;
        }
        h6 {
            text-align: center;
            font-size: x-large;
            margin-top: 20px;
        }
        .table td, .table th {
            padding: 15px;
        }
    </style>
</head>
<body>

<header>
    <nav class="header-nav">
        <a class="btn btn-info" href="@Url.Action("homepage", "Authed")">
            <i class="fas fa-house"></i> Home
        </a>
        <a class="create-link btn btn-success" asp-action="Create">Create New</a>
    </nav>
</header>

<main>
    <div class="container">
        <h6 class="text-center" style="font-size: x-large; margin-top: 20px;">GenericName</h6>
        <br>
        <table id="myTable" class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>@Html.DisplayNameFor(model => model.Name)</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model) {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.Name)</td>
                        <td>
                            <div class="btn-group" role="group" aria-label="Actions">
                                <a class="btn btn-sm edit-link" asp-action="Edit" asp-route-id="@item.Id">
                                    <i class="fas fa-edit"></i> Edit
                                </a>
                                @* <a class="btn btn-sm delete-link" asp-action="Delete" asp-route-id="@item.Id">
                                    <i class="fas fa-trash-alt"></i> Delete
                                </a> *@
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</main>

<!-- Include jQuery and DataTables -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<script>
    $(document).ready(function() {
        $('#myTable').DataTable();
    });
</script>

</body>
</html>